{% set version = "0.2.3" %}

package:
  name: antic
  version: {{ version }}

source:
  url: https://github.com/wbhart/antic/archive/v{{ version }}.tar.gz
  sha256: 78a06f67352d7a94905a5399ef0f0add1a34e90fb0c30b8dbdedf8254393e9dd

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('antic', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - libflint >=2.7
    - gmp
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/antic/nf.h      # [unix]
    - test -f $PREFIX/lib/libantic.so         # [linux]
    - test -f $PREFIX/lib/libantic.dylib      # [osx]

about:
  home: https://github.com/wbhart/antic
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Algebraic Number Theory In C

extra:
  recipe-maintainers:
    - saraedum
