{% set version = "0.2.5" %}

package:
  name: antic
  version: {{ version }}

source:
  url: https://github.com/wbhart/antic/archive/v{{ version }}.tar.gz
  sha256: 7b236b6226d5730cf66d492f1562c34d4dcf1bdc8775fec2330f560332ab05c1

build:
  number: 3
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('antic', max_pin='x.x') }}    # [not osx]
    # On macOS, the library is called libantic-0.2.5.dylib, so we have to pin
    # exactly, see https://github.com/wbhart/antic/issues/80
    - {{ pin_subpackage('antic', max_pin='x.x.x') }}  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - cmake  # [win]
    - ninja  # [win]
  host:
    - libflint
    - gmp  # [not win]
    - mpir  # [win]
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/antic/nf.h             # [unix]
    - test -f $PREFIX/lib/libantic.so                # [linux]
    - test -f $PREFIX/lib/libantic.dylib             # [osx]
    - if not exist %LIBRARY_INC%\antic\nf.h exit 1   # [win]
    - if not exist %LIBRARY_LIB%\antic.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\antic-0.dll exit 1  # [win]

about:
  home: https://github.com/wbhart/antic
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Algebraic Number Theory In C

extra:
  recipe-maintainers:
    - saraedum
