{% set version = "0.2.4" %}

package:
  name: antic
  version: {{ version }}

source:
  url: https://github.com/wbhart/antic/archive/v{{ version }}.tar.gz
  sha256: 517d53633ff9c6348549dc6968567051b2161098d2bc395cb40ecc41e24312c6
  patches:
    - 0001-no-r.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('antic', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - autotools_clang_conda  # [win]
    - make  # [not win]
  host:
    - libflint >=2.7
    - gmp  # [not win]
    - mpir  # [win]
    - mpfr

test:
  commands:
    - test -f $PREFIX/include/antic/nf.h      # [unix]
    - test -f $PREFIX/lib/libantic.so         # [linux]
    - test -f $PREFIX/lib/libantic.dylib      # [osx]

about:
  home: https://github.com/wbhart/antic
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Algebraic Number Theory In C

extra:
  recipe-maintainers:
    - saraedum
